### PR TITLE
Fix #112 : 2nd discarded log in replication_buffer should be finally sent.

### LINKED ISSUE #112: Removing Voter and NonVoter nodes
Hi,

I'm in the process of implementing an application based on async-raft, and I ran into a problem regarding cluster membership.

Adding NonVoters and then promoting them to Voters work without any hiccups. However, unfortunately, I fail to understand how node removal works.

When removing a Voter node via `change_membership`, the removed node's state is changed to NonVoter, and a replication stream from the cluster Leader still remains. Therefore, when I shut down the removed node (which is, at that point, in NonVoter state), the Leader floods the console with errors regarding timed out RPCs. I tried changing the `replication_lag_threshold` and the `max_payload_entries` in the hope of the Leader giving up, but I had no luck.
A related problem is the removal of a NonVoter node, which had not been promotod to Voter: I simply don't know how to shut down the replication stream from the Leader to the NonVoter.

Can you please explain what is the correct way of completely removing Voters or NonVoters?

### PR DESCRIPTION
**Pull request by drmingdrmer**
Internally when replication goes to LaggingState(a non-leader lacks a lot of logs), the
ReplicationCore purges `outbound_buffer` and `replication_buffer` and then send all
**committed** logs found in storage.

Thus if there are uncommitted logs in `replication_buffer`, these logs will never have a chance to
be replicated, even when replication goes back to LineRateState.
Since LineRateState only replicates logs from `ReplicationCore.outbound_buffer` and
`ReplicationCore.replication_buffer`.

This test ensures that when replication goes to LineRateState, it tries to re-send all logs
found in storage(including those that are removed from the two buffers.

This is the second patch to solve #112 and includes all changes in #122.

Related:
#119

@battila7

### CODE REVIEW

**Comment by battila7** [comment]
@drmingdrmer 
#122 already checked.

Nice catch, seems to be quite a particular case. Definitely looks good to me!

**Comment by thedodd** [comment]
> Thus if there are uncommitted logs in replication_buffer, these logs will never have a chance to
be replicated, even when replication goes back to LineRateState.
Since LineRateState only replicates logs from ReplicationCore.outbound_buffer and
ReplicationCore.replication_buffer.

When transitioning to LineRateState, the lagging algorithm is required to hit the head entry in the log before cutting back over to LineRate ... so, did you actually see an issue where logs were being skipped?

**Comment by thedodd** [comment]
Also @drmingdrmer take a look at `frontload_outbound_buffer` and how it is used by the LineRate replication controller. We strictly check with the Raft core to ensure that the very next index which needs to be sent to the follower is the next index in our buffer, ensuring that there are no gaps.

**Comment by drmingdrmer** [comment]
@thedodd 
It won't go into `frontload_outbound_buffer` at all, Because `next_buf_index` is `None`, which I already explained in the PR description and in the code comment:
The log is purged from buffers when replication switching to LaggingState.

**Comment by thedodd** [comment]
@drmingdrmer you have to consider the loop. Each of the different state controllers works in a loop waiting on events. In this case, if the outbound buffers are empty, it waits for data to come in from the Raft core. Once data comes in from the Raft core, alignment is checked. Alignment is literally ALWAYS checked before any data is sent.

**Comment by drmingdrmer** [comment]
> @drmingdrmer you have to consider the loop. Each of the different state controllers works in a loop waiting on events. In this case, if the outbound buffers are empty, it waits for data to come in from the Raft core. Once data comes in from the Raft core, alignment is checked. Alignment is literally ALWAYS checked before any data is sent.

@thedodd 
This problem is that if there are no new logs coming, some old logs will never be replicated.

**Comment by drmingdrmer** [comment]
@thedodd 
Every of my PR has a corresponding test file to reproduce the problem.

Run the test in this PR without the fix in `replication/mod.rs`, you'll see the test will time out waiting for the last log committed on the leader.

**Pull request closed without merging**
