### PR TITLE
Fix #112 : 1st empty conflict

### LINKED ISSUE #112: Removing Voter and NonVoter nodes
Hi,

I'm in the process of implementing an application based on async-raft, and I ran into a problem regarding cluster membership.

Adding NonVoters and then promoting them to Voters work without any hiccups. However, unfortunately, I fail to understand how node removal works.

When removing a Voter node via `change_membership`, the removed node's state is changed to NonVoter, and a replication stream from the cluster Leader still remains. Therefore, when I shut down the removed node (which is, at that point, in NonVoter state), the Leader floods the console with errors regarding timed out RPCs. I tried changing the `replication_lag_threshold` and the `max_payload_entries` in the hope of the Leader giving up, but I had no luck.
A related problem is the removal of a NonVoter node, which had not been promotod to Voter: I simply don't know how to shut down the replication stream from the Leader to the NonVoter.

Can you please explain what is the correct way of completely removing Voters or NonVoters?

### PR DESCRIPTION
**Pull request by drmingdrmer**
`append_entries` should get a response with non-none ConflictOpt even if the entries in the message is empty.
Otherwise if no conflict is found the leader will never be able to sync logs to a new added
NonVoter, until a next log, is proposed on the leader.

### CODE REVIEW

**Comment by drmingdrmer** [comment]
@battila7
By trying to solve #119 I found several other related problems. The patches are all ready in my forked repo.
This is the first patch that fixes #112 .

@thedodd 
Hi man, do you have time on weekdays to help me to review these pr? The world needs you!

**Comment by battila7** [comment]
@drmingdrmer 
Hi,

thanks for tagging me, in the past few days I did not have the chance to read through my GitHub notifications. 

This is something I also noticed in the past, but did not pay much attention to it. Great changes!

One thing though: I think, it might be beneficial to split the attached test into two cases to help readability and somewhat reduce the scope of the individual tests.

**Comment by drmingdrmer** [comment]
> One thing though: I think, it might be beneficial to split the attached test into two cases to help readability and somewhat reduce the scope of the individual tests.

@battila7
The test tests two things: a conflict is expected even when there are no entries in the message, no matter whether there are logs in the store or no logs at all.

They are all about the behavior of a message without entries.

Did you mean to split these two cases into two files? 🤔 I'd be comfortable with either choice.`:DDD`

**Comment by thedodd** [comment]
@drmingdrmer I actually made the code like this to address a different larger issue. Heartbeats need to be treated as heartbeats, and not considered as part of a normal replication process, otherwise it can cause subtle issues with folks attempting to replicate large data payloads — which ... is probably not a good idea for them to be doing. Anyway, that is why the code is crafted as such. 

@drmingdrmer however, the issue you are describing is actually not true. The leader will begin attempting to replicate logs, actual logs (not empty replication payloads), as soon as the NonVoter is detected and added. As such, at most a new NonVoter would only receive a few heartbeats as most before data replication actually starts. Once data replication starts, ConflictOpt data will also be returned.

What is the actual issue you are seeing @drmingdrmer ??? Are you seeing a large period of time before data begins to flow to a new NonVoter?

**Comment by drmingdrmer** [comment]
> @drmingdrmer I actually made the code like this to address a different larger issue. Heartbeats need to be treated as heartbeats, and not considered as part of a normal replication process, otherwise it can cause subtle issues with folks attempting to replicate large data payloads — which ... is probably not a good idea for them to be doing. Anyway, that is why the code is crafted as such.

What are the **subtle** issues? 🤔 
 
> @drmingdrmer however, the issue you are describing is actually not true. The leader will begin attempting to replicate logs, actual logs (not empty replication payloads), as soon as the NonVoter is detected and added. As such, at most a new NonVoter would only receive a few heartbeats as most before data replication actually starts. Once data replication starts, ConflictOpt data will also be returned.
>
> What is the actual issue you are seeing @drmingdrmer ??? Are you seeing a large period of time before data begins to flow to a new NonVoter?

@thedodd 

https://github.com/async-raft/async-raft/pull/125/files#diff-4634600d3985364ed888fb5ae0f5fdf4e64520005ff82a154038b773001452a5R26-R54

With the branch in #125 :

`cargo test -p async-raft --test bug_empty_entries`

You see a timeout waiting for log to replicate to NonVoter:

`Error: timeout wait for n1.last_log_index -> 2 latest metrics: RaftMetrics { id: 1, state: NonVoter, current_term: 1, last_log_index: 0, last_applied: 0, current_leader: Some(0), membership_config: MembershipConfig { members: {1}, members_after_consensus: None } }`

**Pull request closed without merging**
