### PR TITLE
Everything is now implemented directly on top of Tokio.

### LINKED ISSUE #11: Periodic snapshots/compaction.
Snapshot creation needs to be triggered based on configuration & distance from last snapshot, not just based on leader detecting that a node is far behind.

- This will just be a simple mechanism which compares the distance of the `last_log_index` from the last snapshot point, and will trigger a compaction as needed.
- Needs state representation to ensure it does not overlap/conflict with receiving a snapshot from the leader (which will take precedence).

### LINKED ISSUE #13: Tracing.
Instrument code with https://github.com/tokio-rs/tracing

### LINKED ISSUE #15: Refactor snapshot handler.
Code quality in this module is not so great (`src/raft/install_snapshot.rs`). Async/await will help a lot once it is ready, and once acitx is fut03 compat.

### LINKED ISSUE #34: Emit metrics updates based on changes, not on interval.
Will probably bundle this up as a `0.5` release, and the staged `0.4.3` changes might just roll up into that.

### LINKED ISSUE #36: `snapshot_dir` in `Config`?
It looks like the `snapshot_dir` field of `Config` might actually be a detail of the `Storage` implementation - I couldn't find another place it's used in the Raft implementation, it's just passed by the user when constructing their storage. Could this be left up to the storage implementer?

### LINKED ISSUE #38: Cut over to async/await once available.
This will also cover upgrading the underlying version of tokio, which actix has already done with the 0.9 release.

### LINKED ISSUE #40: Upgrade actix version to 0.9
Upgrade actix to version >= 0.9 so applications using actix 0.9 could use actix-raft

### LINKED ISSUE #46: InitialState does not implement Default
The [documentation for `GetInitialState`](https://docs.rs/actix-raft/0.4.3/actix_raft/storage/struct.GetInitialState.html) says:

> If no such entry exists due to being the first time the node has come online, then the default value for InitialState should be used.

However, `InitialState` does not implement `Default`, and neither does `HardState`.

### LINKED ISSUE #49: Decouple snapshots from the filesystem
As we discussed previously, I'm using an in-memory store as I don't need persistence, but I would like to be able to use the snapshot/log-compaction feature to avoid the memory usage growing indefinitely and to make it easier for new nodes to catch up with the leader.

Unfortunately, the current snapshot feature seems intricately coupled with the filesystem, in that actix-raft directly streams results from a file on disk. While I think it would be nice to keep this as a "drop-in" snapshot implementation, I think this should be an implementation detail of the Storage type. Furthermore, I think it's a little odd how some of the APIs operate at a "chunk" level, whereas some operate via file names.

What I would like to see is for `CreateSnapshot` and `InstallSnapshot` to each be split into two parts. such that the second part could be shared between them, so we'd have something like:

- `CreateSnapshot`
  This would take a log range and would save a corresponding snapshot *somewhere* (filesystem, memory, wherever). It would return an opaque snapshot ID.

- `SupplySnapshot`
  This would take no arguments. It would return a new opaque snapshot ID and something implementing `AsyncWrite`. Instead of the current "chunk"-based API, this crate should simply write the snapshot data into the `AsyncWrite` object, calling `flush` where necessary so that there's no need for the per-chunk callback.

- `InstallSnapshot`
  This would take a log range and an opaque snapshot ID produced by a call to `CreateSnapshot` or `SupplySnapshot` from the same node and would implement the logic to compact the log. To aid this, the "path" in EntrySnapshotPointer would be replaced with the opaque snapshot ID. The storage implementation could also use this point to delete other snapshots (as actix-raft should guarantee not call either of the other two methods whilst `InstallSnapshot` is in progress).

Finally, the directory path from the initial config would be dropped, as it will no longer be necessary.

### LINKED ISSUE #51: Inconsistency with Raft spec
From the spec:
> To prevent this problem, servers disregard RequestVote RPCs when they believe a current leader exists. Specifically, if a server receives a RequestVote RPC within the minimum election timeout of hearing from a current leader, it does not update its term or grant its vote.

The code does not appear to implement this behaviour.

On the other hand, implementing this behaviour seems like it could cause problems: if one node in a cluster temporarily loses connectivity then its "term" may increase beyond the rest of the cluster. When connectivity returns, this node will never be able to rejoin the cluster: it will always refuse AppendEntriesRequests from the leader due to its own "term" being ahead, but it will always fail to win VoteRequests because other nodes will still be receiving heartbeats from the leader.

I can only assume that servers are expected to update themselves with the "term" in a VoteRequest, even if that VoteRequest is going to be ignored due to this reason. However, this would seem to defeat the point of this change, which is intended to prevent ex-members from disrupting the cluster unnecessarily.

### LINKED ISSUE #52: "Invalid path" test fails on windows because path is actually valid
I now have this 😛 

image

### LINKED ISSUE #54: Message passing latency?
Looking at the design of actix-raft, I wonder what the rationale for using this many individual actors is.  IIUC there are at least 10 messages involved for every client request, with metrics even more. Benchmarking actix actors I found that message passing between actors isn't _that_ cheap, and should only be used where necessary (e.g. decoupling blocking operations). 

How about making actors optional and allowing implementation of the components via simple traits (too)?

### LINKED ISSUE #60: Lagging replication streams will grow indefinitely
I may be misreading, but it appears that lagging replication streams will accumulate new messages indefinitely. Items are added to the `buffered_outbound` field when in the `Lagging` state:
```rust
    fn handle(&mut self, msg: RSReplicate<D>, ctx: &mut Self::Context) -> Self::Result {
        // Always update line commit & index info first so that this value can be used in all AppendEntries RPCs.
        self.line_commit = msg.line_commit;
        self.line_index = msg.entry.index;

        // Get a mutable reference to an inner buffer if permitted by current state, else return.
        match &mut self.state {
            // NOTE: exceeding line rate buffer size is accounted for in the `handle_append_entries_response` handler.
            RSState::LineRate(inner) => inner.buffered_outbound.push(msg.entry),
            RSState::Lagging(inner) => inner.buffered_outbound.push(msg.entry), // <-- Here
            _ => return Ok(()),
        };

        self.drive_state(ctx);
        Ok(())
    }
```

But the buffered output field is only truncated when in the `LineRate` state:
```rust
            // If running at line rate, and our buffered outbound requests have accumulated too
            // much, we need to purge and transition to a lagging state. The target is not able to
            // replicate data fast enough.
            if let RSState::LineRate(inner) = &self.state {
                if inner.buffered_outbound.len() > (self.config.max_payload_entries as usize) {
                    return Box::new(self.transition_to_lagging(ctx)); // <-- Here
                }
            }
```

It's unclear why the `Lagging` state needs to store `buffered_outbound` messages at all, since it will fetch messages from the storage layer as needed.

(BTW, I've been writing my own Raft implementation on top of `act-zero` using this crate as a reference where the paper is unclear, and it's really quite enjoyable.)

### LINKED ISSUE #61: Fallback conflict-resolution method uses the wrong term
When the conflict optimization is not used (conflict_opt is None) the replication stream decrements its `match_index`. After doing so, it should also fetch the corresponding `match_term` from the storage layer.

Failing to do this will result in sending an incorrect `prev_log_term` in future `AppendEntries` requests, which will then be rejected, causing the replication to become stuck.

### LINKED ISSUE #62: Joint consensus not implemented correctly
I believe votes are counted incorrectly during joint consensus.

Firstly, during this phase, votes should be counted separately for the two clusters. Quote from the spec:
> Agreement (for elections and entry commitment) requires separate majorities from both the old and new configurations.

Currently the code only tracks a single vote counter in the candidate state.

Secondly, this is not so clearly explained, but I believe a candidate which will be removed after a membership change, which has received the log entry containing the membership change, should only count the vote for itself in the "old" vote counter, but not the "new" vote counter.

### PR DESCRIPTION
**Pull request by thedodd**
- [x] setup the two admin functions on the Raft interface.
- [x] update InstallSnapshot RPC handler to always seek to the target offset if not already present.
- [x] finish client response variant for leader forwarding.
- [x] add config param for `cluster_name`. This has no significance to the protocol overall, but will be useful in debugging, tracing and diagnostics when dealing with a mutli-raft setup.
- [x] docs (only core & replication remaining).
- [x] finish up self-compaction routine.
- [x] ensure all code is properly instrumented with the tracing.
- [x] add docs on how to do static filtering (eg, in release mode strip everything that is not > info &c).
- [x] ensure leader does not count itself in commitment when it is stepping down.
- [x] cut over to Actions.
- [x] remove the concept of Committed vs Applied response conditions. Should only be Applied.
- [x] update ClientRequestEntry to have an enum type for the response channel to accommodate Raft-initiated requests which do not use a response from the storage engine.
- [x] latest membership must not be stored as part of the "hard state". It must only ever be the latest config entry in the log.
    - update current config only after the membership change hits the log.
    - remove membership from hardstate. It must only ever come from the log (via reverse search from the end of the log).
    - update the append entries RPC handler to update its membership config if it ever has to delete logs.
    - update the install snapshot handler to update its membership after installing a snapshot to ensure it is using the latest.
- [x] finish primary integration test suite.
- [x] do a review of algorithmic test coverage, and ensure everything is covered.
  - [x] add test coverage for stepdown.
  - [x] ~~add test coverage for recovery from lagging state under write load conditions. Recovery should occur before end of write load.~~ This is partially covered by other tests. Open an issue to have a more in-depth test covering this case.
- [x] finish updating guide, and update references to the guide throughout the code. Add a section to the guide on application specific requirements, mostly pertinent to §8 of the spec.
- [x] build the `Raft.client_read` interface for ensuring the callee Raft node is still the cluster leader (to guard against stale reads). 
- [x] probably move this repo over to async-raft org.

----

### audit
- [x] check all channel select tasks to ensure channels will not cause issues if closed.
- [x] ensure no tasks will block heartbeats.
- [x] review fatal storage error handling.
- [x] ensure metrics are being emitted whenever observability data is updated.

----

Closes #11 
Closes #13 
Closes #15 
Closes #34 
Closes #36 
Closes #38 
Closes #40 
Closes #46 
Closes #49 
Closes #51 
Closes #52 
Closes #54 
Closes #60 
Closes #61 
Closes #62

### CODE REVIEW

**Comment by oronsh** [comment]
Hey, this change is amazing. Can you please explain why you've decided to forsake `actix` and rewrite the lib directly on top of `tokio`? I am super interested :)

**Comment by thedodd** [comment]
Hey @oronsh that's a great question. I was debating with myself quite a lot as to whether or not I should make these changes. Ultimately my reasoning came down to a few things:
- tokio as a project definitely moves much faster than actix. I wanted to update this project much earlier to be able to leverage async/await and simplify the code, however actix was much slower in getting around to that.
- there will intuitively be more applications being built directly on tokio, and shifting this projects focus to address that fact seems logical.
- these changes to not preclude the use of actix. Whereas the previous (4.x and prior) versions required the use of actix, which may have been a hindrance for folks that only need tokio.

**Comment by oronsh** [comment]
Thank you @thedodd ! 
I think you're right, and I think that it's not gonna be much of a problem to integrate this lib to `actix` if one wanted it once it runs on top of `tokio`.

Seems like `tokio` is becoming to standard de facto for network and async apps in rust :)

**Comment by thedodd** [comment]
@oronsh agreed. There is definitely a lot still happening in the async world in Rust. async-std, smol, new actor frameworks popping up here and there; however, betting on Tokio seems like a pretty safe bet. And for a project like this, I think that is important.

**Comment by thedodd** [comment]
Ok, quick update for anyone watching: I do believe that this branch is now feature complete.

Remaining work:
- tests
- docs
- guide

**Comment by jamessewell** [comment]
This looks amazing!

**Pull request merged**
